import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { AuthShell } from "../components/AppShell";

export default function Login() {
  const navigate = useNavigate();
  const [errors, setErrors] = useState<{ email?: string; password?: string }>({});
  return <AuthShell><div className="form-card login-card"><h1>Welcome back</h1><p>Sign in to continue to Perennial.</p><form className="form-grid" noValidate onSubmit={(event) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const email = String(form.get("email") ?? "").trim(); const password = String(form.get("password") ?? ""); const nextErrors: { email?: string; password?: string } = {}; if (!email) nextErrors.email = "Email is not valid."; else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) nextErrors.email = "Email is not valid."; if (!password || password.length < 8) nextErrors.password = "Password must be at least 8 characters."; if (Object.keys(nextErrors).length) { (formElement.elements.namedItem("email") as HTMLInputElement).value = ""; (formElement.elements.namedItem("password") as HTMLInputElement).value = ""; setErrors({ email: nextErrors.email ?? "Email is not valid.", password: nextErrors.password ?? "Password must be at least 8 characters." }); return; } setErrors({}); navigate("/verify-code"); }}><div className="form-field"><label htmlFor="email">Email Address</label><input id="email" name="email" type="email" placeholder="Enter your Email" onFocus={() => setErrors((current) => ({ ...current, email: undefined }))} aria-invalid={Boolean(errors.email)} />{errors.email && <p className="field-error" role="alert">{errors.email}</p>}</div><div className="form-field"><label htmlFor="password">Password</label><input id="password" name="password" type="password" placeholder="Enter your password" onFocus={() => setErrors((current) => ({ ...current, password: undefined }))} aria-invalid={Boolean(errors.password)} />{errors.password && <p className="field-error" role="alert">{errors.password}</p>}</div><div className="login-actions"><button className="forgot-link" type="button" onClick={() => navigate("/forgot-password")}>Forgot password?</button><button className="btn-primary" type="submit">Sign in</button></div><p className="login-signup">Don’t have an account? <button className="inline-link" type="button" onClick={() => navigate("/signup")}>Create account</button></p></form></div></AuthShell>;
}
