import { useState } from "react";
import AppShell, { CompanyBadge, Toast, TrashIcon } from "../components/AppShell";
import { useWatchlist } from "../components/watchlistStore";
import { companies } from "../data";

export default function Watchlist() {
  const [query, setQuery] = useState(""); const [toast, setToast] = useState<"success" | "error" | null>(null); const { isWatched, remove } = useWatchlist();
  const filtered = companies.filter((company) => isWatched(company.ticker) && `${company.name} ${company.ticker} ${company.sector}`.toLowerCase().includes(query.toLowerCase()));
  const removeCompany = (ticker: string) => { remove(ticker); setToast("success"); };
  return <AppShell title="Your Watchlist" subtitle="Active items tracked for analysis."><div className="watchlist-toolbar"><span className="asset-pill">All Assets</span><span className="watchlist-count">{filtered.length} companies</span></div><div className="panel"><div className="form-field" style={{ marginBottom: 22 }}><label htmlFor="company-search">Investment portfolio</label><input id="company-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search stocks, tickers, events (e.g. NVDA, RBLX)..." /></div><div className="table-wrap"><table className="data-table watchlist-table"><thead><tr><th>Company name</th><th>Sector</th><th>Sentiment pulse</th><th>Confidence</th><th>Signal status</th><th>Current price</th><th /></tr></thead><tbody>{filtered.map((company) => <tr key={company.ticker}><td><CompanyBadge company={company}/></td><td><span className="sector-text">{company.sector}</span></td><td><span className={`tag ${company.sentiment === "Neutral" ? "tag-neutral" : company.sentiment === "Watch" ? "tag-watch" : ""}`}>● {company.sentiment}</span></td><td><strong>{company.score}</strong></td><td><span className={company.change.startsWith("+") ? "signal-up" : "signal-down"}>{company.change.startsWith("+") ? "↑" : "↓"}</span></td><td><strong>${company.ticker === "NVDA" ? "214.17" : company.ticker === "MSFT" ? "532.27" : company.ticker === "COST" ? "948.13" : "248.98"}</strong><small className={company.change.startsWith("+") ? "metric-positive" : "tag-watch"}>{company.change}</small></td><td><button className="trash-button" onClick={() => removeCompany(company.ticker)} aria-label={`Remove ${company.name} from watchlist`}><TrashIcon /></button></td></tr>)}</tbody></table></div>{filtered.length === 0 && <p className="metric-label">No companies match that search.</p>}<p className="end-of-list">End of watchlist</p></div>{toast && <Toast type={toast} message="Removed from your Watchlist" onDone={() => setToast(null)} />}</AppShell>;
}
